version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
  # General Go dependencies, updated weekly
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "**/rootfs"
    target-branch: "hardened-nginx-1.15.x" # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    schedule:
      interval: "weekly"
    groups:
      go:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/*

  # K8s dependencies, updated monthly
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "**/rootfs"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/* # Allow it through the gate
    groups:
      k8s-dependencies:
        patterns:
          - k8s.io/*
          - sigs.k8s.io/* # Bundle it into the same PR