#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

# If #GIT_TAG is present, then we build base images for all supported platforms, 
# pushing them to dockerhub for use in the package stage. They must be pushed, this 
# an inherent limitation of the buildx cache. See https://github.com/moby/buildkit/issues/2343
if [[ -n "$GIT_TAG" ]] && [ "$GITHUB_ACTIONS" = "true" ]; then
    ARCH="amd64 arm64" PLATFORMS="linux/amd64,linux/arm64" TAG=${NGINX_TAG} make -C images/nginx push
else
    # Only build the images for the current host platform, using regular docker build
    docker buildx use default
    TAG=${NGINX_TAG} make -C images/nginx build
fi
