#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

if ! command -v kind &> /dev/null; then
  ./scripts/e2e-test-install-deps
fi

SKIP_IMAGE_CREATION=false SKIP_E2E_IMAGE_CREATION=true make kind-e2e-test
