#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

# If running e2e locally over and over, you can skip image creation
SKIP_IMAGE_CREATION=${SKIP_IMAGE_CREATION:-false} NGINX_BASE_IMAGE=${BASE_IMAGE}-e2e make kind-e2e-test BUILDER=default

