name: Run Fossa Scan

on:
  push:
    branches:
      # nginx-1.9.x-fix, nginx-1.10.x-fix (in future) and so on
      - "nginx-*-fix"
  # For manual scans.
  workflow_dispatch:

jobs:
  fossa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read FOSSA token
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/org/rancher/fossa/push token | FOSSA_API_KEY_PUSH_ONLY

      - name: FOSSA scan
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ env.FOSSA_API_KEY_PUSH_ONLY }}
          run-tests: false
