name: Publish Support Images
on: 
  workflow_dispatch: {}

# Supports out-of-band publishing of supporting images, such as kube-webhook-certgen.
# We also handle publishing of these supporting images in the main release workflow, 
# but this allows us to publish updates to these images without needing to cut a new release 
# of the entire ingress-nginx controller.

permissions:
  contents: read

jobs:
  kube-webhook-certgen:
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication

    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    # This is a roundabout OP, since the Makefile defaults to this value,
    # but the publish-image action requires a tag, that it then passses to the Makefile
    - name: Set Tag
      run: |
        KWC_TAG=$(cat ./images/kube-webhook-certgen/TAG)
        echo "KWC_TAG=$KWC_TAG" >> $GITHUB_ENV

    # Only pull vault secrets if the repository is rancher
    - name: "Read secrets"
      if: github.repository_owner == 'rancher'
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_TOKEN ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry | PRIME_REGISTRY ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username | PRIME_REGISTRY_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password | PRIME_REGISTRY_PASSWORD
    
    - name: Check if image already exists on DockerHub
      id: certgen_exists
      run: |
        REPO="${{ github.repository_owner }}/kube-webhook-certgen"
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${REPO}/tags/${KWC_TAG}")
        if [[ "$STATUS" == "200" ]]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Check if image already exists on Prime Registry
      id: prime_certgen_exists
      run: |
        # Short-circuit and assume the image exists if this is not the rancher repository
        if [[ "${{ github.repository_owner }}" != "rancher" ]]; then
          echo "prime_exists=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        REPO="${{ env.PRIME_REGISTRY }}/rancher/kube-webhook-certgen"
        REPO="${{ env.PRIME_REGISTRY }}/rancher/kube-webhook-certgen"
        if skopeo inspect "docker://${REPO}:${KWC_TAG}" 1> /dev/null; then
          echo "prime_exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "prime_exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Login to Container Registry with Rancher Secrets
      if: github.repository_owner == 'rancher' && ( steps.certgen_exists.outputs.exists != 'true' || steps.prime_certgen_exists.outputs.prime_exists != 'true' )
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_TOKEN }}

    # For forks, setup docker login with GHA secrets
    - name: Login to Container Registry
      if: github.repository_owner != 'rancher' && steps.certgen_exists.outputs.exists != 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      if: steps.certgen_exists.outputs.exists != 'true' || steps.prime_certgen_exists.outputs.prime_exists != 'true'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: steps.certgen_exists.outputs.exists != 'true' || steps.prime_certgen_exists.outputs.prime_exists != 'true'
      uses: docker/setup-buildx-action@v3

    - name: Setup Docker Credentials
      if: github.repository_owner != 'rancher' && steps.certgen_exists.outputs.exists != 'true'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $GITHUB_ENV
        echo "DOCKER_TOKEN=$DOCKER_TOKEN" >> $GITHUB_ENV

    - name: Build and push kube-webhook-certgen image
      if: steps.certgen_exists.outputs.exists != 'true' || steps.prime_certgen_exists.outputs.prime_exists != 'true'
      uses: rancher/ecm-distro-tools/actions/publish-image@9cc9d787c12b5ed1acdeb504e4ff59511ffd39c9 # v0.62.0
      with:
        image: kube-webhook-certgen
        tag: ${{ env.KWC_TAG }}
        make-target: push -C ./images/ NAME=kube-webhook-certgen
        public-repo: ${{ github.repository_owner }}
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_TOKEN }}
        push-to-public: ${{ steps.certgen_exists.outputs.exists != 'true' }}

        prime-repo: rancher
        prime-registry: ${{ env.PRIME_REGISTRY }}
        prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
        prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}
        push-to-prime: ${{ github.repository_owner == 'rancher' && steps.prime_certgen_exists.outputs.prime_exists != 'true' }}